datasource:
  driver: org.h2.Driver
  url: jdbc:h2:file:~/QRScan
  username: sa
  password:
jpa:
  show-sql: true
  dialect: org.hibernate.dialect.H2Dialect
  current-session-context-class: thread
  hbm2ddl:
    auto: update
  hibernate:
    dbcp:
      initialSize: 5
      maxTotal: 20
      maxIdle: 10
      minIdle: 5
      maxWaitMillis: -1
